# configs/model_config_improved.yaml
# Enhanced model configuration

# Tokenizer
tokenizer_name: "bert-base-uncased"

# Architecture dimensions
vocab_size: 30522  # Will be overridden by tokenizer
hidden_size: 512   # Increased from 384
encoder_layers: 6  # Increased from 4
decoder_layers: 6  # Increased from 4
num_attention_heads: 8  # Increased from 6
intermediate_size: 2048  # Increased from 1536
max_position_embeddings: 384
latent_size: 256   # Increased from 192

# Regularization
dropout_rate: 0.1

# Generation parameters
num_refinement_steps: 5   # Increased from 3
confidence_threshold: 0.85  # Slightly reduced to allow more updates

use_gradient_checkpoint: true