# configs/training_config.yaml
# Training configuration

# Dataset 
train_file: null  # Set to path for real data
val_file: null
test_file: null
val_split: 0.1
num_train_samples: 1000  # Used for synthetic data
num_val_samples: 100     # Increased from 10 to 100 for better validation
num_test_samples: 100

# Training parameters
batch_size: 16
learning_rate: 5e-5
weight_decay: 0.01
max_epochs: 10
steps_per_epoch: 63  # num_train_samples / batch_size (approx)
use_lr_scheduler: true
gradient_clip_val: 1.0

# Hardware/Performance
num_workers: 4
precision: "16-mixed"  # Use mixed precision
accumulate_grad_batches: 1

# Logging
log_every_n_steps: 10
save_top_k: 2

# Paths
output_dir: "./checkpoints"
log_dir: "./logs"